#!/usr/bin/env perl
use strict;
use warnings FATAL => "all";
use 5.010_000;
use Data::Dumper;
use autodie;
use FindBin;
use lib "$FindBin::Bin/lib";
use Run::BowtieBuild;

END {close STDOUT}
$| = 1;

use Getopt::Euclid qw( :vars<opt_> );
use Pod::Usage;

pod2usage(-verbose => 99,-sections => [qw/NAME SYNOPSIS OPTIONS/]) if $opt_help;

unless ($opt_c2t xor $opt_g2a){
    say STDERR "Either -c2t and -g2a are required (but not both!)";
    exit 255;
}

my $conversion = $opt_c2t ? 'c2t' : 'g2a';
bowtie_build(file => $opt_reference, bs => $conversion, rc => 1);

=head1 NAME

bs-bowtie-build.pl - Convert genomes to c2t and bowtie-build

=head1 SYNOPSIS

Usage examples:

 bs-bowtie-build.pl [options]...

=head1 REQUIRED ARGUMENTS

=over

=item  <reference>

=for Euclid
    reference.type:        readable

=back

=head1 OPTIONS

=over

=item  -c2t

=item  -g2a

=item --help | -h

=back

=cut
