#!/usr/bin/env perl
use strict;
use warnings FATAL => "all";
use 5.010_000;
use Data::Dumper;
use autodie;
use FindBin;
use lib "$FindBin::Bin/lib";
use Run::BowtieBuild;

END {close STDOUT}
$| = 1;

use Getopt::Euclid qw( :vars<opt_> );
use Pod::Usage;

pod2usage(-verbose => 99,-sections => [qw/NAME SYNOPSIS OPTIONS/]) 
if $opt_help || ! $opt_reference || ! -f $opt_reference || ! ($opt_c2t xor $opt_g2a);

unless ($opt_c2t xor $opt_g2a){
    say STDERR "Either -c2t and -g2a are required (but not both!)";
    exit 255;
}

my $conversion = $opt_c2t ? 'c2t' : 'g2a';
bowtie_build(
    file => $opt_reference, 
    noref => $opt_noref, 
    bs => $conversion, 
    rc => 1,
    version => $opt_version,
);

=head1 NAME

bs-bowtie-build.pl - Convert genomes to c2t and bowtie-build

=head1 SYNOPSIS

Usage examples:

 bs-bowtie-build.pl [options]...

=head1 OPTIONS

=over

=item  <reference>

=for Euclid
    reference.type:        readable


=over

=item  -c2t

=item  -g2a

=item  -v <ver> | --version <ver>

bowtie version. default 1.

=for Euclid
    ver.default:     1
    ver.type:        readable
    ver.type:        int, ver >= 1 && ver <= 2

=item --noref | -r

From bowtie-build manual: 

  Do not build the NAME.3.ebwt and NAME.4.ebwt portions of the index, which
  contain a bitpacked version of the reference sequences and are used for
  paired-end alignment.

=item --help | -h


=back

=cut
