#!/usr/bin/env perl
use strict;
use warnings FATAL => "all";
use 5.010_000;
use Data::Dumper;
use autodie;
use IO::All;

my $file = shift || die "$0 file.sam";
if ($file =~ /\.sam$/){
    system("sam2bam.pl $file");
    system("samtools tview ". $file =~ s/\.sam$/\.bam/r);
}
else{
    system("samtools tview $file");
}
